steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}',
      '--build-arg', 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}',
      '--build-arg', 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}',
      '--build-arg', 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}',
      '--build-arg', 'NEXTAUTH_URL=${_NEXTAUTH_URL}',
      '--build-arg', 'GOOGLE_SHEET_ID=${_GOOGLE_SHEET_ID}',
      '--build-arg', 'GOOGLE_CLIENT_EMAIL=${_GOOGLE_CLIENT_EMAIL}',
      '--build-arg', 'GOOGLE_PRIVATE_KEY=${_GOOGLE_PRIVATE_KEY}',
      '-t', 'gcr.io/lengolf-forms/lengolf-forms',
      '.'
    ]

images:
  - 'gcr.io/lengolf-forms/lengolf-forms'