# Use Node.js 20 (Latest LTS)
FROM node:20-alpine AS builder

# Set build arguments
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG GOOGLE_SHEET_ID
ARG GOOGLE_CLIENT_EMAIL
ARG GOOGLE_PRIVATE_KEY

# Debug environment variables
RUN echo "NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}"
RUN echo "NEXTAUTH_URL: ${NEXTAUTH_URL}"

# Set environment variables from build arguments
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID
ENV GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL
ENV GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy all files
COPY . .

# Build application
RUN npm run build

# Production image
FROM node:20-alpine AS runner

# Set environment variables
ENV NODE_ENV=production
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV GOOGLE_SHEET_ID=$GOOGLE_SHEET_ID
ENV GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL
ENV GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY

WORKDIR /app

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Debug in runner
RUN echo "Runner NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}"
RUN echo "Runner NEXTAUTH_URL: ${NEXTAUTH_URL}"

# Expose port
EXPOSE 3000

# Set the command to run the app
CMD ["node", "server.js"]