name: CD

on:
  push:
    branches: [ master, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Debug Environment
      run: |
        echo "Build for branch: ${GITHUB_REF##*/}"
        echo "Has NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET != '' }}"

    - name: Build and push to Container Registry
      env:
        DEPLOY_URL: ${{ github.ref == 'refs/heads/dev' && 'https://lengolf-forms-dev-1071951248692.asia-southeast1.run.app' || secrets.NEXTAUTH_URL }}
      run: |
        gcloud builds submit --config=cloudbuild.yaml \
        --substitutions=_NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}",\
        _NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}",\
        _GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}",\
        _GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}",\
        _NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}",\
        _NEXTAUTH_URL="$DEPLOY_URL",\
        _GOOGLE_SHEET_ID="${{ secrets.GOOGLE_SHEET_ID }}",\
        _GOOGLE_CLIENT_EMAIL="${{ secrets.GOOGLE_CLIENT_EMAIL }}",\
        _GOOGLE_PRIVATE_KEY='${{ secrets.GOOGLE_PRIVATE_KEY }}'

    - name: Deploy to Cloud Run
      run: |
        IMAGE_URL="gcr.io/lengolf-forms/lengolf-forms:latest"
        SERVICE_NAME=${{ github.ref == 'refs/heads/dev' && 'lengolf-forms-dev' || 'lengolf-forms' }}
        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE_URL \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated \
          --update-env-vars NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}",NEXTAUTH_URL="${{ github.ref == 'refs/heads/dev' && 'https://lengolf-forms-dev-1071951248692.asia-southeast1.run.app' || secrets.NEXTAUTH_URL }}"